adopt/urls.py
from django.urls import path

from . import views

app_name = "adopt"
urlpatterns = [
    path('', views.my_adoptions, name="my_adoptions"),
    path('<int:cat_id>/', views.request_adoption, name="adopt"),
    path('delete/', views.delete_adoption, name="delete_adoption"),
]

cats/urls.py
from django.urls import path

from . import views

app_name = "cats"
urlpatterns = [
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/adopted", views.AdoptedDetailView.as_view() , name="adopted_detail")
]

petadoption/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path("search/", include("search.urls")),
    path('cats/', include("cats.urls")),
    path('adopt/', include("adopt.urls")),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adopt/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User

from cats.models import Cat 

class AdoptionRequest(models.Model):
    datetime = models.DateTimeField(auto_now_add=True)
    
    class Status(models.IntegerChoices):
        PENDING = 1, _("Pending")
        APPROVED = 2, _("Approved")
        REJECTED = 3, _("Rejected")

    status = models.IntegerField(default=Status.PENDING, choices=Status.choices)

    # For rejected requests
    reason = models.CharField(max_length=100, blank=True, null=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cat = models.ForeignKey(Cat, on_delete=models.CASCADE)

    def __str__(self):
        return "{} wants to adopt {}!".format(self.user, self.cat.name)

    def request_exists(user, cat, status=Status.PENDING):
        """
        This function returns True if a request by <user> for <cat>, optionally with
        status=<status> exists
        """
        return AdoptionRequest.objects.filter(user=user, cat=cat, status=status).exists()

adopt/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views import generic, View
from django.core.exceptions import PermissionDenied, BadRequest
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import AdoptionRequest
from cats.models import Cat

@login_required
def my_adoptions(request):
    context = {}

    # Display only the adoption request for this user
    user_adoptions = AdoptionRequest.objects.filter(user=request.user)

    # Separate the adoption requests in three lists depending on the
    # status, so that they can be displayed separately
    context["has_requests"] = user_adoptions.exists()
    context["approved_list"] = user_adoptions.filter(status=AdoptionRequest.Status.APPROVED).all()
    context["pending_list"] = user_adoptions.filter(status=AdoptionRequest.Status.PENDING).all()
    context["rejected_list"] = user_adoptions.filter(status=AdoptionRequest.Status.REJECTED).all()

    return render(request, "adopt/my_adoptions.html", context)

@login_required
def request_adoption(request, cat_id):
    # This view creates an adoption request object in the backend, so
    # the POST method must be used
    if request.method != "POST":
        messages.error(request, 'Adoption requests have to be POSTed!')
        return render(request, "405.html", status=405)

    cat = Cat.objects.get(pk=cat_id)

    # If the cat was already adopted by someone else, then the user
    # can't make a request for it, and should see 404
    if cat.is_adopted:
        return render(request, "404.html", status=404)

    # Check if a PENDING request by that user for that cat already exists,
    # if the user only has REJECTED requests for that cat, then they can try
    # to adopt it again
    if AdoptionRequest.request_exists(request.user, cat):
        return redirect("cats:detail", pk=cat_id)

    # Create the adoption request for the specified cat
    adoption_request = AdoptionRequest(user=request.user, cat=cat)
    adoption_request.save()

    # Redirect user to the "My Adoptions" page
    return redirect("adopt:my_adoptions")

@login_required
def delete_adoption(request):
    # This view deletes an adoption request object in the backend, so
    # the POST method must be used
    if request.method != "POST":
        messages.error(request, 'Adoption deletion requests have to be POSTed!')
        return render(request, "405.html", status=405)

    # A list of adoption request ids to delete is given in the url parameter <to_delete>
    ids_to_delete = request.POST.getlist("to_delete")
    if not ids_to_delete:
        raise BadRequest()

    # If a mistake such as trying to delete a request id belonging to another user, or
    # not existing at all was made in the URL, don't delete anything

    # 1st pass checks that all ids to delete are valid
    adoption_requests = []
    for adoption_id in ids_to_delete:
        adoption_request = get_object_or_404(AdoptionRequest, pk=adoption_id)

        # Check if the request belongs to another user
        if adoption_request.user.id != request.user.id:
            raise PermissionDenied()

        # If the request isn't PENDING, it shouldn't be deleted
        if adoption_request.status != AdoptionRequest.Status.PENDING:
            raise PermissionDenied()
            
        adoption_requests.append(adoption_request)

    # 2nd pass actually performs the deletions
    for adoption_request in adoption_requests:
        adoption_request.delete()

    # Redirect user to the "My Adoptions" page
    return redirect("adopt:my_adoptions")
    

adopt/templates/adopt/my_adoptions.html
{% extends "base.html" %}

{% block content %}

<div class="adoption_container">
	{% if has_requests %}
		<div>
			<h3>Approved requests</h3>
			{% if approved_list %}
				<table>
					<thead>
						<tr>
							<th>Cat</th>
							<th>Date</th>
						</tr>
					</thead>

					<tbody>
						{% for request in approved_list %}
							<tr>
								<td><a href="{% url 'cats:adopted_detail' request.cat.id %}">{{ request.cat.name }}</a></td>
								<td>{{ request.datetime }}</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			{% endif %}
		</div>

		<div>
			<h3>Pending requests</h3>
			{% if pending_list %}
				<form>
					<table>
						<thead>
							<tr>
								<th>Cat</th>
								<th>Date</th>
								<th>Withdraw?</th>
							</tr>
						</thead>

						<tbody>
							{% for request in pending_list %}
								<tr>
									<td><a href="{% url 'cats:detail' request.cat.id %}">{{ request.cat.name }}</a></td>
									<td>{{ request.datetime }}</td>
									<td><input type="checkbox" id="{{ request.id }}" name="to_delete" value="{{ request.id }}"></td>
								</tr>
							{% endfor %}
						</tbody>
					</table>

					<br>
					
					<button type="button" onclick="send_deletion_request()">Withdraw</button>
					<div id="delete_error_msg"></div>
				</form>
			{% endif %}
		</div>

		<div>
			<h3>Rejected requests</h3>
			{% if rejected_list %}
				<table>
					<thead>
						<tr>
							<th>Cat</th>
							<th>Date</th>
							<th>Reason</th>
						</tr>
					</thead>

					<tbody>
						{% for request in rejected_list %}
							<tr>
								{% if request.cat.is_adopted %}
									<td>{{ request.cat.name }}</td>
								{% else %}
									<td><a href="{% url 'cats:detail' request.cat.id %}">{{ request.cat.name }}</a></td>
								{% endif %}
								
								<td>{{ request.datetime }}</td>
								<td>{{ request.reason }}</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			{% endif %}
		</div>
	{% else %}
		<p>You haven't made any adoption requests!</p>
	{% endif %}
</div>
{% endblock %}

{% block scripts %}

{% csrf_token %}
<script>
const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;

function send_deletion_request() {
	var ids_to_delete = [];
	var delete_checkboxes = document.getElementsByName("to_delete");

	// Get the ids to delete
	for (const checkbox of delete_checkboxes) {
		if (checkbox.checked)
			ids_to_delete.push(["to_delete", checkbox.value]);
	}

	// If no requests were selected, don't send any request to
	// the server, and instead show an error message to the user
	if (ids_to_delete.length == 0) {
		document.getElementById("delete_error_msg").innerHTML = "You must select some requests to delete!";
		return;
	}

	// Post the deletion request
	const request = new Request(
	    "{% url 'adopt:delete_adoption' %}",
	    {
	    	body: new URLSearchParams(ids_to_delete),
	        method: 'POST',
	        headers: {'X-CSRFToken': csrftoken},
	        mode: 'same-origin',
	        redirect: 'follow'
	    }
	);

	fetch(request)
	.then(response => {
		// Redirect to the url returned by the server
		window.location.replace(response.url);
    })
    .catch(function(err) {
        console.log(err + " url: " + url);
    });
}
</script>
{% endblock %}