accounts/urls.py
from django.contrib.auth import views as auth_views 
from django.urls import path, reverse_lazy  
from django.conf.urls.static import static

from . import views

app_name="accounts"

urlpatterns = [
    path("register/", views.RegistrationView.as_view(), name="registration"),
    path("register/done", views.registration_done, name="registration_done"),
    path( \
        "login/", \
        auth_views.LoginView.as_view(template_name="accounts/login.html"), \
        name="login" \
    ),
    path( \
        "logout/", \
        auth_views.LogoutView.as_view(template_name="accounts/logged_out.html"), \
        name="logout" \
    ),
    path( \
        "password_reset/", \
        auth_views.PasswordResetView.as_view(template_name="accounts/password_reset_form.html", \
                                             email_template_name="accounts/password_reset_email.html", \
                                             success_url=reverse_lazy('accounts:password_reset_done')), \
        name="password_reset" \
    ),
    path( \
        "password_reset/done/", \
        auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"), \
        name="password_reset_done" \
    ),
    path( \
        "reset/<uidb64>/<token>/", \
        auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html", \
                                                    success_url=reverse_lazy('accounts:password_reset_complete')), \
        name="password_reset_confirm" \
    ),
    path( \
        "reset/done/", \
        auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"), \
        name="password_reset_complete" \
    ),
]

cats/urls.py
from django.urls import path

from . import views

app_name = "cats"
urlpatterns = [
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/adopted", views.AdoptedDetailView.as_view() , name="adopted_detail")
]

petadoption/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path("search/", include("search.urls")),
    path('cats/', include("cats.urls")),
    path('adopt/', include("adopt.urls")),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django.forms import ModelForm, PasswordInput, ValidationError, CharField
from django.contrib.auth.models import User

class RegistrationForm(ModelForm):
    class Meta:
        model = User
        fields = ["username", "email", "password", "first_name", "last_name"]
        widgets = {
            "password": PasswordInput,
        }
    
    repeat_password = CharField(label='Repeat password', \
                                widget=PasswordInput, \
                                required = True)

    field_order = ["username", "email", "password", "repeat_password", \
                   "first_name", "last_name"]

    def clean(self):
        """
        Override clean() to validate that the password and
        repeat_password fields have the same string.
        """
        cleaned_data = super().clean()

        password = cleaned_data.get("password")
        repeat_password = cleaned_data.get("repeat_password")

        # If both values were validated successfully, perform the check
        if password and repeat_password:
            if password != repeat_password:
                err = ValidationError(
                    "The password must be the same in both fields.",
                    code = "password_mismatch"
                )

                self.add_error("repeat_password", err)

    def save(self, commit=True):
        """
        Override so that the password will be hased using set_password
        before it is stored in the model
        """
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])

        if commit:
            user.save()

        return user





    

accounts/views.py
from django.views.generic.edit import CreateView
from .forms import RegistrationForm
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, redirect

class RegistrationView(CreateView):
    form_class = RegistrationForm
    template_name = "accounts/registration.html"
    success_url = reverse_lazy("accounts:registration_done")

def registration_done(request):
    # If the user is logged in redirect them to the home page
    if request.user.is_authenticated:
        return redirect(reverse("index"))

    return render(request, "accounts/registration_complete.html")

accounts/templates/accounts/logged_out.html
{% extends "base.html" %}

{% block content %}

<div class="account_container">
    <p>
        Logged out successfully. <a href="{% url 'accounts:login' %}">Login again?</a>
    </p>
</div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}

<div class="account_container">
    <div class="account_form">
        {% if form.errors %}
            <p>Your username and password didn't match. Please try again.</p>
        {% endif %}

        {% if next %}
            {% if user.is_authenticated %}
                <p>Your account doesn't have access to that page. To proceed,
                please login with an account that has access.</p>
            {% else %}
                <p>You must login to see that page.</p>
            {% endif %}
        {% endif %}

        <form method="post" action="{% url 'accounts:login' %}">
            {% csrf_token %}
            <table>
                <tr>
                    <td>{{ form.username.label_tag }}</td>
                    <td>{{ form.username }}</td>
                </tr>
                <tr>
                    <td>{{ form.password.label_tag }}</td>
                    <td>{{ form.password }}</td>
                </tr>
            </table>

            <input type="submit" value="Login">
            <input type="hidden" name="next" value="{{ next }}">
        </form>

        <p>
            <a href="{% url 'accounts:registration' %}">First time user?</a>
            <br>
            <a href="{% url 'accounts:password_reset' %}">Lost password?</a>
        </p>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends "base.html" %}

{% block content %}
    
<p>The password has been changed!</p>

{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}

<div class="account_container">
    <div class="account_form">
        {% if validlink %}
            <p>Please enter (and confirm) your new password.</p>

            <form action="" method="post">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>{{ form.new_password1.errors }}
                            <label for="id_new_password1">New password:</label></td>
                        <td>{{ form.new_password1 }}</td>
                    </tr>
                    <tr>
                        <td>{{ form.new_password2.errors }}
                            <label for="id_new_password2">Confirm password:</label></td>
                        <td>{{ form.new_password2 }}</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><input type="submit" value="Change my password"></td>
                    </tr>
                </table>
            </form>
        {% else %}
            <h1>Password reset failed</h1>
            <p>The password reset link was invalid, possibly because it has already been used. Please request a new password reset.</p>
        {% endif %}
    </div>
</div>

{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends "base.html" %}

{% block content %}

<p>We've emailed you instructions for setting your password. If they haven't arrived in a few minutes, check your spam folder.</p>

{% endblock %}

accounts/templates/accounts/password_reset_email.html
 <!DOCTYPE html>
<html lang="en">

<head>
	<title>{% block title %}Pet Adoption Home{% endblock %}</title>

	{% load static %}
	<link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
	<link rel="stylesheet" href="{% static 'style.css' %}">

	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
</body>

</html>

accounts/templates/accounts/password_reset_form.html
{% extends "base.html" %}

{% block content %}

<div class="account_container">
    <div class="account_form">
        {% if form.email.errors %}
            {{ form.email.errors }}
        {% endif %}

        <p> Enter your email to receive a password reset link: </p>

        <form action="" method="post">
            {% csrf_token %}

            <p>{{ form.email }}</p>
            
            <input type="submit" class="btn btn-default btn-lg" value="Reset password">
        </form>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/registration.html
{% extends "base.html" %}

{% block content %}

<div class="account_container">
    <div class="account_form">
        <p>Submit your personal info:</p>

        {{ form.non_field_errors }}

        <form method="post" action="{% url 'accounts:registration' %}">
            {% csrf_token %}
            <table>
                <tbody>
                    {% for field in form %}
                        <tr>
                            <td>{{ field.label_tag }}</td>
                            <td>{{ field }}</td>
                        </tr>

                        {% if field.errors %}
                            <tr>
                                <td colspan="2">{{ field.errors }}</td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
            <input type="submit" value="Submit">
        </form>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/registration_complete.html
{% extends "base.html" %}

{% block content %}
   
<div class="account_container">
	<h2>Registration successful!</h2>  
</div>

{% endblock %}