cats/urls.py
from django.urls import path

from . import views

app_name = "cats"
urlpatterns = [
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/adopted", views.AdoptedDetailView.as_view() , name="adopted_detail")
]

petadoption/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path("search/", include("search.urls")),
    path('cats/', include("cats.urls")),
    path('adopt/', include("adopt.urls")),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path

from . import views

app_name = "search"
urlpatterns = [
    path('', views.search, name="search"),
    path('results/', views.SearchResultsView.as_view(), name="results"),
]

search/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views import generic
from django.db.models import Q

from cats.models import Cat

def search(request):
    ages = [x[1] for x in Cat.Age.choices]
    sexes = [x[1] for x in Cat.Sex.choices]
    colors = [x[1] for x in Cat.Color.choices]

    context = {"age_choices": ages, "sex_choices": sexes, \
               "color_choices": colors}

    return render(request, "search/search.html", context)

class SearchResultsView(generic.ListView):
    model = Cat
    template_name = "search/cat_display.html"

    def get_queryset(self):
        ages = list(map(Cat.get_internal_age, self.request.GET.getlist("age")))
        sexes = list(map(Cat.get_internal_sex, self.request.GET.getlist("sex")))
        colors = list(map(Cat.get_internal_color, self.request.GET.getlist("color")))

        is_vaccinated = self.request.GET.get("vaccinated") 
        is_house_trained = self.request.GET.get("house_trained")
        is_sterilized = self.request.GET.get("sterilized")

        object_list = Cat.objects

        # Don't apply a multiple choice filter if no choices or all choices are selected
        if ages and len(ages) != len(Cat.Age.values):
            # Compose an OR expression because many values might be provided for that field
            ages_q = [Q(age=age) for age in ages]
            ages_or = ages_q[0]
            for age_q in ages_q[1:]:
                ages_or |= age_q

            object_list = object_list.filter(ages_or)

        if sexes and len(sexes) != len(Cat.Sex.values):
            sexes_q = [Q(sex=sex) for sex in sexes]
            sexes_or = sexes_q[0]
            for sex_q in sexes_q[1:]:
                sexes_or |= sex_q
                
            object_list = object_list.filter(sexes_or)

        if colors and len(colors) != len(Cat.Color.values):
            colors_q = [Q(color=color) for color in colors]
            colors_or = colors_q[0]
            for color_q in colors_q[1:]:
                colors_or |= color_q
                
            object_list = object_list.filter(colors_or)

        if is_vaccinated == "true":
            object_list = object_list.filter(is_vaccinated=True)

        if is_house_trained == "true":
            object_list = object_list.filter(is_house_trained=True)

        if is_sterilized == "true":
            object_list = object_list.filter(is_sterilized=True)

        # Don't display cats that were already adopted
        object_list = object_list.exclude(is_adopted=True)

        return object_list.all()

search/templates/search/cat_display.html
{% extends "base.html" %}

{% block logo %}
{% endblock %}

{% block navbar %}
{% endblock %}

{% block content %}

<div id="display_container">
	{% if cat_list %}
	    {% for cat in cat_list %}
        	<div class="cat_display">
        		<a href="{% url 'cats:detail' cat.id %}">
        			<img src="{{ cat.image.url }}" alt="{{ cat.name }}">
        		</a>
        		<span class="cat_name">{{ cat.name }}</span>
        	</div>
	    {% endfor %}
	{% else %}
	    <p>No pets are available :(</p>
	{% endif %}
</div>

{% endblock %}

{% block footer %}
{% endblock %}

search/templates/search/search.html
{% extends "base.html" %}

{% block content %}

<div id="search_container">
	<form>
		<label>Age:</label>
		<span class="checkbox_container">
			{% for age in age_choices %}
				<input type="checkbox" id="{{ age }}" name="age" value="{{ age }}" onchange="fetch_results()">
				<label for="{{ age }}">{{ age }}</label>
			{% endfor %}
		</span>
		<button type="button" onclick="set_all_checkboxes_by_name('age')">All </button>
		<button type="button" onclick="reset_checkboxes_by_name('age')">Reset</button>
		<br>

		<label>Sex:</label>
		<span class="checkbox_container">
			{% for sex in sex_choices %}
				<input type="checkbox" id="{{ sex }}" name="sex" value="{{ sex }}" onchange="fetch_results()">
				<label for="{{ sex }}">{{ sex }}</label>
			{% endfor %}
		</span>
		<button type="button" onclick="set_all_checkboxes_by_name('sex')">All</button>
		<button type="button" onclick="reset_checkboxes_by_name('sex')">Reset</button>
		<br>

	  	<label>Color:</label>
	  	<span class="checkbox_container">
			{% for color in color_choices %}
				<input type="checkbox" id="{{ color }}" name="color" value="{{ color }}" onchange="fetch_results()">
				<label for="{{ color }}">{{ color }}</label>
			{% endfor %}
		</span>
		<button type="button" onclick="set_all_checkboxes_by_name('color')">All</button>
		<button type="button" onclick="reset_checkboxes_by_name('color')">Reset</button>
		<br>

		<input type="checkbox" id="vaccinated" name="vaccinated" onchange="fetch_results()">
		<label for="vaccinated">Must be vaccinated</label><br>

		<input type="checkbox" id="house_trained" name="house_trained" onchange="fetch_results()">
		<label for="house_trained">Must be house-trained</label><br>

		<input type="checkbox" id="sterilized" name="sterilized" onchange="fetch_results()">
		<label for="sterilized">Must be sterilized</label><br><br>
	</form>
</div>

<!-- Empty section that will be filled by the Javascript -->
<div id="results"></div>

{% endblock %}

{% block scripts %}
<script>

window.onload = (event) => {
    fetch_results();
};

function get_checked(name) {
	var checked_values = [];
	var checkbox_group = document.getElementsByName(name);

	for (const choice of checkbox_group) {
		if (choice.checked)
			checked_values.push([name, choice.value]);
	}

	return checked_values;
}

function reset_checkboxes_by_name(name) {
	var checkbox_group = document.getElementsByName(name);

	for (const choice of checkbox_group) {
		choice.checked = false;
	}

	// Call fetch_results to apply the condition reset to the results
	fetch_results();
}

function set_all_checkboxes_by_name(name) {
	var checkbox_group = document.getElementsByName(name);

	for (const choice of checkbox_group) {
		choice.checked = true;
	}

	// Call fetch_results to apply the condition change to the results
	fetch_results();
}

function fetch_results() {
	var age_checked = get_checked("age");
	var sex_checked = get_checked("sex");
	var color_checked = get_checked("color");

	var vaccinated = ["vaccinated", document.getElementById("vaccinated").checked];
	var house_trained = ["house_trained", document.getElementById("house_trained").checked];
	var sterilized = ["sterilized", document.getElementById("sterilized").checked];

	var param_list = age_checked.concat(sex_checked).concat(color_checked);
    param_list.push(vaccinated);
    param_list.push(house_trained);
    param_list.push(sterilized);

	var searchParams = new URLSearchParams(param_list);

	fetch("{% url 'search:results' %}?" + searchParams)
	.then(response => {
		return response.text();
	})
	.then(html => {
		document.getElementById("results").innerHTML = html;    
	})
	.catch(err => {
		console.error(err);
		document.getElementById("results").innerHTML = "Search failed...";
	});
}

</script>
{% endblock %}