accounts/urls.py
from django.contrib.auth import views as auth_views 
from django.urls import path, reverse_lazy  
from django.conf.urls.static import static

from . import views

app_name="accounts"

urlpatterns = [
    path("register/", views.RegistrationView.as_view(), name="registration"),
    path("register/done", views.registration_done, name="registration_done"),
    path( \
        "login/", \
        auth_views.LoginView.as_view(template_name="accounts/login.html"), \
        name="login" \
    ),
    path( \
        "logout/", \
        auth_views.LogoutView.as_view(template_name="accounts/logged_out.html"), \
        name="logout" \
    ),
    path( \
        "password_reset/", \
        auth_views.PasswordResetView.as_view(template_name="accounts/password_reset_form.html", \
                                             email_template_name="accounts/password_reset_email.html", \
                                             success_url=reverse_lazy('accounts:password_reset_done')), \
        name="password_reset" \
    ),
    path( \
        "password_reset/done/", \
        auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"), \
        name="password_reset_done" \
    ),
    path( \
        "reset/<uidb64>/<token>/", \
        auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html", \
                                                    success_url=reverse_lazy('accounts:password_reset_complete')), \
        name="password_reset_confirm" \
    ),
    path( \
        "reset/done/", \
        auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"), \
        name="password_reset_complete" \
    ),
]

adopt/urls.py
from django.urls import path

from . import views

app_name = "adopt"
urlpatterns = [
    path('', views.my_adoptions, name="my_adoptions"),
    path('<int:cat_id>/', views.request_adoption, name="adopt"),
    path('delete/', views.delete_adoption, name="delete_adoption"),
]

cats/urls.py
from django.urls import path

from . import views

app_name = "cats"
urlpatterns = [
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/adopted", views.AdoptedDetailView.as_view() , name="adopted_detail")
]

petadoption/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path("search/", include("search.urls")),
    path('cats/', include("cats.urls")),
    path('adopt/', include("adopt.urls")),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path

from . import views

app_name = "search"
urlpatterns = [
    path('', views.search, name="search"),
    path('results/', views.SearchResultsView.as_view(), name="results"),
]

templates/405.html
{% extends "base.html" %}

{% block content %}

<h1>405 - Method Not Allowed</h1>

{% endblock %}

templates/base.html
 <!DOCTYPE html>
<html lang="en">

<head>
	<title>{% block title %}Pet Adoption Home{% endblock %}</title>

	{% load static %}
	<link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
	<link rel="stylesheet" href="{% static 'style.css' %}">

	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
	{% block logo %}
	<header>
		<a href="{% url 'index' %}">
			<img src="{% static 'images/logo.png' %}">
		</a>
	</header>
	{% endblock %}
	
	{% block navbar %}
	<nav>
		<a href="{% url 'search:search' %}">Search</a>

		{% if user.is_authenticated %}
			<a href="{% url 'adopt:my_adoptions' %}">My Adoptions</a>
			<a href="{% url 'accounts:logout' %}?next={{ request.path }}">Log out</a>
		{% else %}
			<a href="{% url 'accounts:login' %}?next={{ request.path }}">Sign in</a>
		{% endif %}
	</nav>
	{% endblock %}
	
	<main>
	{% block content %}
	{% endblock %}

	{% block messages %}
	{% if messages %}
		<ul class="messages">
			{% for message in messages %}
				<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			{% endfor %}
		</ul>
	{% endif %}
	{% endblock %}
	</main>
	
	
	{% block footer %}
	<footer>
		<div>
			<a href="https://www.freepik.com/free-vector/blank-white-notepaper-design_16397306.htm
			#query=diary%20page&position=0&from_view=keyword&track=ais">Image by rawpixel.com</a> 

			on Freepik, the cats in the logo are from "Azumanga Daioh".
		</div>
	</footer>
	{% endblock %}
	
	{% block scripts %}
	{% endblock %}
</body>

</html> 

templates/index.html
{% extends "base.html" %}

{% block content %}
<h1 style="text-align:center;">
	This is a cat adoption website. Give them the home they deserve!
</h1>
<br>
<h2 style="text-align:center;">
	You can find cats such as these here:
</h2>

{% include "search/cat_display.html" with cat_list=cat_list %}
{% endblock %}